defaults:
  - _self_

dataset: cifar10 

# cosine
# dist_dir: "/vols/bitbucket/saravanan/distributional-mf/outputs/default/cifar"
# dist_checkpoint_dir: "/vols/bitbucket/saravanan/distributional-mf/outputs/default/cifar/periodic-epoch=284-step=100000.ckpt"

dist_dir: "/vols/bitbucket/saravanan/distributional-mf/outputs/2025-09-03/16-54-27"
dist_checkpoint_dir: "/vols/bitbucket/saravanan/distributional-mf/outputs/2025-09-03/16-54-27/checkpoints/periodic-epoch=284-step=100000.ckpt"

guidance_classifier: "ahsanjavid/convnext-tiny-finetuned-cifar10" 
eval_classifier: "nateraw/vit-base-patch16-224-cifar10"

dist_config: "${dist_dir}/.hydra/config.yaml"

seed: 42
labels_to_sample: [1, 3, 5, 7, 9,]
samples_per_label: 32

hydra:
  run:
    dir: "${dist_dir}/sampling/class_conditional"

use_ema: true

conditional_score: "iwae" # dps, iwae, mc
unconditional_score: null # mc_unconditional

iwae:
  n_samples: 1
  type: "cfm" # cfm, cfm_combined, cfm_approximate

sampling:
  batch_size: 32
  euler_steps: 1000
  clip_each_step: False
  t_eps: 0.001